### ISSUE TITLE
crashing on startup with AMD 2990 WX + 2080ti

### ISSUE THREAD

**Issue by masterkni666** [dje-dev/Ceres#12]
right after loading the ceres.json it crashes with this message

96.625<--1:Ceres user settings loaded from file Ceres.json
96.641<--1:Unhandled exception. System.ComponentModel.Win32Exception (87): The parameter is incorrect.
96.641<--1:   at System.Diagnostics.Process.set_ProcessorAffinityCore(IntPtr value)
96.641<--1:   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value)
96.641<--1:   at Ceres.Base.OperatingSystem.HardwareManager.AffinitizeSingleProcessor() in C:\Ceres-main\src\Ceres.Base\OperatingSystem\HardwareManager.cs:line 91
96.641<--1:   at Ceres.Base.OperatingSystem.HardwareManager.Initialize(Boolean affinitizeSingleProcessor) in C:\Ceres-main\src\Ceres.Base\OperatingSystem\HardwareManager.cs:line 37
96.641<--1:   at Ceres.MCTS.Environment.MCTSEngineInitialization.BaseInitialize() in C:\Ceres-main\src\Ceres.MCTS\Environment\MCTSEngineInitialization.cs:line 40
96.641<--1:   at Ceres.Program.Main(String[] args) in C:\Ceres-main\src\Ceres\Program.cs:line 68

**Comment by masterkni666** [comment]
someone suggested this may have to do with numa cores on the threadripper?

**Comment by dje-dev** [comment]
Worked around with commit 2f09a831099944951f0cfed1d4679a7ff1970c0e. Possibly affinitization will fail on some AMD processors, but will not crash.
