### ISSUE TITLE
Nibbler not working with Castling

### ISSUE THREAD

**Issue by eahova** [dje-dev/Ceres#17]
Fix #15 did fix the UCI eval calls but Nibbler still does not work with Castling.

Seemingly, it both does not return any moves that involve Castling and also crashes the engine if you do Castle.

Example fen:  r1bqkb1r/ppp3p1/2n2p2/3p1n1p/3P4/2P2N1P/PP1NBPP1/R1BQK2R w KQkq - 2 9

In Ceres.exe UCI it returns bestmove e1g1
In Nibbler it shows top move of Qb3

After you castle with White is crashes the engine...

**Comment by fohristiwhirl** [comment]
Some of this might be on Nibbler's end but I can't really test things until there's a release.

**Comment by eahova** [comment]
Looks like Nibbler changes the KQkq into chess960 notation of AHah which isn't supported by Ceres

I added a pull request #21 to at least support the regular chess position of AHah so Nibbler works as you'd expect

**Comment by fohristiwhirl** [comment]
The logic in #21 is wrong, the correct equivalences are:

```
A --> Q
H --> K
a --> q
h --> k
```

**Comment by eahova** [comment]
@fohristiwhirl - thanks for catching...sorry about that...I put in pull request #22 to correct

**Comment by dje-dev** [comment]
Fixed with #22
