### ISSUE TITLE
crashing while running 1000 fixed node test

### ISSUE THREAD

**Issue by masterkni666** [dje-dev/Ceres#4]
<img width="950" alt="stacktrace" src="https://user-images.githubusercontent.com/19353314/103427406-a5cf1180-4b75-11eb-86a1-0720cd8e44a4.PNG">

**Comment by masterkni666** [comment]
crashing at real TC 1sec+0.1

<img width="1145" alt="stacktrace" src="https://user-images.githubusercontent.com/19353314/103430856-3c530100-4b7d-11eb-9895-8309907ec515.PNG">

**Comment by dje-dev** [comment]
It seems that if a search exits immediately (e.g. time exhaustion) then the BestMove is null and this can be dereferenced. However no replication sequence of nodes is obvious. But Ceres should be more defensive in this situation. Related, when presented with a terminal position Ceres aborts upon a "go" command (albeit with a clear message). Consider how to handle this. LC0 responds by outputting an invalid move "bestmove a1a1" which does not seem idea either.

**Comment by masterkni666** [comment]
This entire issue may just be a cutechess bug? The current position should have been adjudicated as draw but given to ceres anyways.

<img width="1432" alt="Capture" src="https://user-images.githubusercontent.com/19353314/103465996-a1c9fd80-4cf5-11eb-9cbb-4d812c5867ec.PNG">

**Comment by dje-dev** [comment]
This issue is long since resolved.
