### ISSUE TITLE
Problem in Nibbler when both WDL and DTZ present

### ISSUE THREAD

**Issue by dje-dev** [dje-dev/Ceres#44]
(Bigo)
"Well normally when I reach syzygy Ceres crashes with Nibbler but here it's working fine since I only have WDL and not DTZ"

Possibly same as #38

**Comment by imBigo** [comment]
If MultiPV > 1 and Syzygy of the current fen position has DTZ, Ceres crashes.

**Comment by dje-dev** [comment]
Addressed, see #38.
