### ISSUE TITLE
Typo bug in Position.CheckDrawBasedOnMaterial

### ISSUE THREAD

**Issue by BrianH12345** [dje-dev/Ceres#48]
Line 197 of Position.cs appears to contain a typo. One of the bishopCountThem's should be an Us:

`else if (bishopCountThem != 2 || bishopCountThem != 2) // two bishops same side may not be a draw`

**Comment by dje-dev** [comment]
Thank you for the careful reading of the code and identifying this bug. This has been fixed and will soon be pushed.
