### ISSUE TITLE
error "ErrorInvalidPtx"

### ISSUE THREAD

**Issue by fidemasterjuliano** [dje-dev/Ceres#49]
a error runnig Cere 0.90 - error "ErrorInvalidPtx".

cant work

**Comment by dje-dev** [comment]
This indicates that the kernels in compiled into the binary do not support your GPU. As indicated in the release notes, it is known that current 1080 and below cards are not supported (but I believe I can improve this situation in the very near future). Please indicate the model of GPU you are using. Thank you.

**Comment by fidemasterjuliano** [comment]
Thank you ! 
My notebook card : Nvidia GeForce GTX 1060 6 Gib

**Comment by Mbr18** [comment]
For me also the same error with 0.90-rc1:
-CUDA device 0: NVIDIA GeForce GTX 1060 6GB SMs: 10 Mem: 6gb.
-Desktop GPU (NVIDIA 471.11 Win 10 64).

**Comment by dje-dev** [comment]
After doing more research, the problem with the 1080/1070/1060 cards is that for these cards "NVIDIA has severely limited FP16 CUDA performance." However Ceres runs only in FP16 mode so unfortunately it is not possible to use Ceres 0.90 and above with these cards. (However v0.89 is functional).
