### ISSUE TITLE
WDL numbers not updating?

### ISSUE THREAD

**Issue by whelanh** [dje-dev/Ceres#51]
In running Ceres 0.91a today via Nibbler, Ceres quickly found the "right" move of Nd5...per Stockfish :-)   However I noticed the WDL numbers did not update (continuing to show the move as unattractive even though the Q value got increasingly positive).  Is this a Nibbler issue?
![Screenshot (1)](https://user-images.githubusercontent.com/11835229/126155731-537eba86-6aec-416c-92bb-36c98c71aaee.png)

**Comment by whelanh** [comment]
FYI: I was running Lc0 net #69626

**Comment by rooklift** [comment]
Position is `r4rk1/pp1bp1b1/2np1pp1/6Pq/2P5/1PN2PP1/P1NQPKBn/R6R w - - 0 17`

**Comment by rooklift** [comment]
Checking for myself, near the start of the search I received the line:

`info depth 10 seldepth 2 time 600 nodes 1387 score cp -103 wdl 84 288 628 tbhits 0 nps 2311 multipv 16 pv c3d5  string M= 129`

And later I received

`info depth 16 seldepth 12 time 26126 nodes 139291 score cp 42 wdl 84 288 628 tbhits 0 nps 5332 multipv 2 pv c3d5 c6e5 d5e7 g8f7 e7d5 f6g5 f2g1 f8h8 a1f1 e5c6 f1f2  string M= 140`

So it seems WDL didn't get updated.

**Comment by dje-dev** [comment]
Ceres shows the W/D/L of the static position, not the average W/D/L over the subtree. But your observation (thanks!) makes it clear that subtree average W/D/L would be much more interesting useful. The fix is pushed and will be bundled into the next release.

**Comment by whelanh** [comment]
Thank you very much. Ceres is a very interesting engine!
