### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Jaglo2** [dje-dev/Ceres#53]
I have Windows7, but I see the message: 

"
|=========================================================|
| Ceres - A Monte Carlo Tree Search Chess Engine          |
|                                                         |
| (c) 2020- David Elliott and the Ceres Authors           |
|   With network backend code from Leela Chess Zero.      |
|                                                         |
|  Version 0.91b  Use help to list available commands.    |
|=========================================================|

Fatal Error. Windows Version 7 or above required.
"

What's the matter?

**Comment by dje-dev** [comment]
I see the problem. The Ceres code currently looks like the following, which compares against the version number, looking for at least 7. However I found in the Microsoft documentation that Windows 7 is actually returned as "version 6" - seems illogical! I will correct this for the next release. I believe one user already made this change in the source code and my have succeeded in running on Windows 7, so maybe you will have some luck.
```
      else if (isWindows && System.Environment.OSVersion.Version.Major < 7)
      {
        errorString = "Windows Version 7 or above required.";
      }

+------------------------------------------------------------------------------+
|                    |   PlatformID    |   Major version   |   Minor version   |
+------------------------------------------------------------------------------+
| Windows Vista      |  Win32NT        |         6         |          0        |
| Windows 2008       |  Win32NT        |         6         |          0        |
| Windows 7          |  Win32NT        |         6         |          1        |
| Windows 2008 R2    |  Win32NT        |         6         |          1        |
| Windows 8          |  Win32NT        |         6         |          2        |
| Windows 8.1        |  Win32NT        |         6         |          3        |
+------------------------------------------------------------------------------+
| Windows 10         |  Win32NT        |        10         |          0        |
+------------------------------------------------------------------------------+
```
