### ISSUE TITLE
The engine doesn't thinking

### ISSUE THREAD

**Issue by gabrielp10031978** [dje-dev/Ceres#55]
Hello,
I have Nvidia Geforce GTX 1060 6 Gb, I installed Microsoft .NET 5.0, I copied these three dlls from LC0 distribution ZIP file, but I don't know what weights file to use, because the engine doesn''t start thinking.
I try to use:
-https://training.lczero.org/networks/1
-https://tests.stockfishchess.org/nns
-69722_value_focus_2.gz
But the engine does not work.
Please help me.
Thanks.

**Comment by JamesLear92** [comment]
On the release notes it says:

If installation issues are encountered, please note these most common causes:
NVIDIA 1060, 1070, 1080 and earlier generation GPUs are not directly supported

I suspect your GTX1060 isn't supported

**Comment by gabrielp10031978** [comment]
Thanks Mr
