### ISSUE TITLE
PGN database used for "Human grandmaster move agreement analysis"

### ISSUE THREAD

**Issue by mikhail-barg** [dje-dev/Ceres#57]
Hi, we are trying to reproduce the results of [Human grandmaster move agreement analysis](https://github.com/dje-dev/Ceres/blob/main/APISamples.md#human-grandmaster-move-agreement-analysis) from API Samples page. It would be great to use same .pgn files that were used in the sample. 

Could you please explain where/how to get this database?

**Comment by dje-dev** [comment]
The pgns were sourced from the following site: https://www.pgnmentor.com/files.html.
I have verified the code as published on this web page still works (for me). I've attached a Linqpad script with the source for your convenience. Good luck!
[API_PlayerGameTest.txt](https://github.com/dje-dev/Ceres/files/7102369/API_PlayerGameTest.txt)

**Comment by mikhail-barg** [comment]
Many thanks!
