### ISSUE TITLE
Ceres doesn't output a readyok (nibbler)

### ISSUE THREAD

**Issue by ZWORX52** [dje-dev/Ceres#65]
When I select the Ceres.exe file in Nibbler as the engine, it (nibbler) gets stuck on "Awaiting readyok from engine". I am wondering why this is happening. My card is an NVIDIA GeForce GTX 980 (Gigabyte subseller). I followed the installation directions.

**Comment by dje-dev** [comment]
I'm sorry, but this card is very old by GPU standards and does not support the fast FP16 mode which Ceres requires.
