### ISSUE TITLE
Support for 40x512 Lc0 networks

### ISSUE THREAD

**Issue by therealkingoftheuniverse** [dje-dev/Ceres#69]
A suggestion to add support for 40x512 Lc0 networks on [Run3 (test78)]. (Maybe only once/if they become better than t60).
(Unless it is already supported, if so then it does not work for me so if that is the case then can someone please help me).
Thanks in advance.

**Comment by dje-dev** [comment]
Now supported for Ampere cards in just released Version 0.96. See https://github.com/dje-dev/Ceres/releases/tag/v0.96.
