### ISSUE TITLE
Please write some code so we can run Ceres on the new Mac Studio

### ISSUE THREAD

**Issue by lex312** [dje-dev/Ceres#73]
20 CPU cores and 64 GPU cores should have more than enough power for Ceres, which will be sooner or later the number one engine and this is also a reason why it is important to make it possible to use Ceres from the beginning of the development on Apple devices.
https://www.apple.com/mac-studio/specs/

**Comment by dje-dev** [comment]
At some future date the excellent Lc0 backends may be generalized to provide an API that other engines such as Ceres could call to leverage a wide range of different hardware devices beyond CUDA (possibly including M1). Duplicating effort specifically for Ceres is not viewed as the best use of limited development resources.
