### ISSUE TITLE
Refuses to play to mate with tablebases enabled

### ISSUE THREAD

**Issue by dje-dev** [dje-dev/Ceres#81]
Ceres with TB enabled will not play until mate. She stops when number of pieces left = TB adj. So in a tournament configuration, with TB enabled, that force engines to play until mate she will not comply since she fails to make a move and will run out of time in this setting...
(from lepned)

**Comment by lepned** [comment]
<img width="633" alt="positionTB" src="https://github.com/dje-dev/Ceres/assets/1504584/1c1188bc-84da-45a2-aace-6b8f71cffcfb">

Ceres (white) played Rxa5 and lost on time

**Comment by dje-dev** [comment]
lepned did further testing and found this was not a bug in Ceres, but a bug in the GUI (now corrected).
