### ISSUE TITLE
Why have tounament feature?

### ISSUE THREAD

**Issue by MrBrain295** [dje-dev/Ceres#83]
Is there a reason for adding this to Ceres rather than relying on people using something like CuteChess?

**Comment by dje-dev** [comment]
Fair question, and CuteChess is indeed excellent software and the gold standard.

However, the tight integration of a tournament feature is very handy (especially for testing and research purposes). It easily allows configuring different Ceres engines (possibly with different internal settings) and running tournaments with them. It also collects many specialized Ceres statistics and logs them to the console (just to give one example, if testing two different settings it will show if the two games played by the different settings were move-for-move identical).
