### ISSUE TITLE
Ceres dont work

### ISSUE THREAD

**Issue by fidemasterjuliano** [dje-dev/Ceres#84]
![Captura de tela 2024-03-23 092339](https://github.com/dje-dev/Ceres/assets/76961855/0294ff92-47dd-42a3-b3d3-77778d8bd04f)

**Comment by dje-dev** [comment]
The error reports the file is corrupt or not a valid Lc0 weights file.

My theory is that this is a compressed Lc0 file that should normally end with a ".gz" so the software knows to first decompress it. If this extension has been stripped off the filename it might cause the problem.
