### ISSUE TITLE
Consider licensing adjustment ("GPL with exceptions")

### ISSUE THREAD

**Issue by dje-dev** [dje-dev/Ceres#9]
From Crem:
While it doesn't have too many authors, it may make sense to re-license it to "GPL with exception" rather than simple "GPL", so that it could be bundled with nvidia cudnn libraries.

From borg
@dje I suggest the exception wording from Leela Zero, they have added TensorRT to the exceptions. See https://github.com/leela-zero/leela-zero/issues/2032

**Comment by dje-dev** [comment]
As also suggested by Crem:
If Ceres will have exceptions to GPL added, maybe it will also make sense to add some Microsoft .net-related libraries there, not only nvidia.
(if it's considered to eventually run it on android, asm-js or google cloud/TPU).

**Comment by mooskagh** [comment]
As also noted in the same chat, it makes sense to have it licensed under "GPLv3 or later" rather than just "GPLv3".
https://www.gnu.org/licenses/gpl-faq.html#VersionThreeOrLater

**Comment by dje-dev** [comment]
Closed with commit 96da170bcf9ea64a10c06dc5f78e1fcc69edfd58
